overhaul DEVELOPMENT (almost done)
samply/blaze pull request #2036
Opened 2024-09-11 13:24 UTC by allentiak

TODO: make Release Checklist use current release workflow

Thanks to FastChat!

https://github.com/lm-sys/FastChat
https://lmarena.ai/

2024-09-11 15:06 UTC, alexanderkiel requested changes

2024-09-11 15:06 UTC, alexanderkiel commented on DEVELOPMENT.md
> +Every public function should have a spec. Function specs are declared in a namespace with the suffix `_spec` appended to the function's namespace. Public module-level function specs reside in the `sr
_spec -> -spec

2024-09-11 15:54 UTC, allentiak commented on DEVELOPMENT.md
> +### Pure Functions
Yeap.
After all, they all discuss coding conventions.

2024-09-11 15:55 UTC, allentiak commented on DEVELOPMENT.md
> +3. Run `docker build -t blaze:latest .` to build the Docker image.
@alexanderkiel 
If you point me to the frontend steps, I could add them as see how the document looks afterwards.

2024-09-11 16:05 UTC, allentiak commented on DEVELOPMENT.md
> +## Release Checklist (TODO: use current release workflow)
I mean the workflow you currently use to create the releases.
The workflow currently detailed here corresponds to the `git-flow`-based workflow you used to follow.

2024-09-11 19:50 UTC, allentiak commented on DEVELOPMENT.md
> +Blaze is built as a single Docker image, along with an uberjar for standalone use.
Could you please point me to it?
I cannot find it either on https://github.com/samply/blaze/releases nor on https://hub.docker.com/r/samply/blaze/tags...

2024-09-11 20:52 UTC, allentiak commented on DEVELOPMENT.md
> +8. Merge the release branch back into develop.
You mean step 8, right?

2024-09-12 06:24 UTC, alexanderkiel commented on DEVELOPMENT.md
> +Blaze is built as a single Docker image, along with an uberjar for standalone use.
It is a separate image: https://hub.docker.com/r/samply/blaze-frontend/tags

2024-09-12 06:25 UTC, alexanderkiel commented on DEVELOPMENT.md
> +3. Run `docker build -t blaze:latest .` to build the Docker image.
It's `make build-frontend`

2024-09-12 06:26 UTC, alexanderkiel commented on DEVELOPMENT.md
> +8. Merge the release branch back into develop.
yes

2024-09-12 06:29 UTC, alexanderkiel requested changes

2024-09-12 06:29 UTC, alexanderkiel commented on DEVELOPMENT.md
> +### Pure Functions
Ok Code Conventions but not Style Guide. So I would see an h2 called Code Conventions here with a h3 follow up called Style Guide.

2024-09-12 08:57 UTC, alexanderkiel requested changes

2024-09-12 08:57 UTC, alexanderkiel commented on DEVELOPMENT.md
> +```make frontend```
It's `make build-frontend`

2024-09-12 09:03 UTC, alexanderkiel approved these changes

2024-09-12 09:25 UTC, merged