Implement CQL ConvertsToDate and ConvertsToDateTime and add new query…
samply/blaze pull request #751
Opened 2022-06-30 07:49 UTC by marlenaMyr

… to test SocialSecurityNumber with ConvertsToInteger

2022-06-30 10:00 UTC, alexanderkiel requested changes

2022-07-03 17:59 UTC, marlenaMyr commented on docs/conformance/cql.md
> +|--------|--------------------|--|---------------|-------|
I have adjusted the table.

2022-07-03 17:59 UTC, marlenaMyr commented on modules/cql/src/blaze/elm/compiler/type_operators.clj
> +        (some? (p/to-date operand now))))))
I added the form.

2022-07-03 18:01 UTC, marlenaMyr commented on modules/cql/src/blaze/elm/compiler/type_operators.clj
> +      (when (some? operand)
Yes you are right! I have removed the unnecessary code.

2022-07-03 18:01 UTC, marlenaMyr commented on modules/cql/src/blaze/elm/compiler/type_operators.clj
> +        (some? (p/to-date-time operand
Done.

2022-07-04 13:38 UTC, alexanderkiel commented on modules/cql/src/blaze/elm/compiler/type_operators.clj
> +  (-form [_]
The test for `form` is missing.

2022-07-04 13:38 UTC, alexanderkiel commented on modules/cql/src/blaze/elm/compiler/type_operators.clj
> +        (some? (p/to-date operand now))))))
The test is missing.

2022-07-04 15:42 UTC, alexanderkiel approved these changes

2022-07-04 15:44 UTC, merged